# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='timestamp',
            new_name='create_time',
        ),
    ]
